Webpage update
NCAR/ADF pull request #154
Opened 2022-04-25 16:07 UTC by justin-richling

This implements the basic upgraded website layout after suggestions in Discussions #114. A sample can be viewed [here](https://project.cgd.ucar.edu/projects/ADF/web_update/f.c6_3_41.FWscHIST.ne30_L58_exner.001_vs_f.e21.FWscHIST.ne30_L48_BL10_cam6_3_041_control.hf.001_1980_1989/index.html)

### Major feature upgrades:

This layout will provide easier user interface and experience such that all plots appear to be on the same page so that the user doesn't have to navigate away to cycle through different variables/plot types/seasons. 

This PR will also add the AMWG comparison tables for model vs model runs. 

The NH and SH Polar plots have been added as well.

The Lat/Lon plots have been reordered such that the two case plots are on one row and the difference plot is below similar to the layout of the Polar plots. This will save space on the page and ensure the plots won't get cut off the browser.

Under each plot type, the available variables have been broken up into categories based off the CAM7 [spreadsheet](https://docs.google.com/spreadsheets/d/17IxS8Du8wkLWefzELex3e3RCr3GrpSr6o5D3GZm8xto/edit?usp=sharing).

Case names in the header have been changed from ```Case 1``` and ```Case 2``` to ```Test Case``` and ```Control Case```.

Table navigation has been added to the main navigation bar at top of page when under the Table plot type category.

If there are many variable categories, the current plots will scroll down the page when the user scrolls.

Clicking on any plot image will bring it up in a new browser tab for zoomable option.

### Files changed:

- ```lib/adf_diag.py```
- ```lib/plotting_functions.py```
- ```lib/website_templates/adf_diag.css```
- ```lib/website_templates/template.html```
- ```lib/website_templates/template_index.html```
- ```lib/website_templates/template_mean_diag.html```
- ```lib/website_templates/template_mean_diag_LatLon.html```
- ```lib/website_templates/template_mean_diag_Zonal.html```
- ```lib/website_templates/template_mean_table.html```
- ```scripts/analysis/amwg_table.py```
- ```scripts/plotting/polar_map.py```
- ```scripts/plotting/zonal_mean.py```

### Files added:

- ```lib/website_templates/template_mean_diag_NHPolar.html```
- ```lib/website_templates/template_mean_diag_SHPolar.html```

### Notes:

The layout is still open to change, but this should be a good start to have user test out.

The Lat/Lon plots seem to be a little small, this is something we can work on after the fact.

AMWG Tables are still on a separate page until we move forward with being able to pull data frame data between scripts.

2022-05-03 14:58 UTC, nusbaume commented
@justin-richling Would you be able to bring in the vector plots as well to this new website layout?  If that is going to be a heavy lift and/or you want some help just let me know.  Also, if you want to test the vector plots then just add `TAUX` and `TAUY` to your variable list and the ADF should generate vector plots for those quantities.  Thanks!

2022-05-04 20:12 UTC, justin-richling commented
@nusbaume Vector plots have been successfully integrated, example [here](https://project.cgd.ucar.edu/projects/ADF/web_update/vector_test/f.e21.FHIST.ne30_L48_BL10_cam6_3_019_plus_CESM2.2.001_zm2.hf_1980_1989_vs_f.e21.FWscHIST.ne30_L48_BL10_cam6_3_019_plus_CESM2.2.001_zm2.hf_1980_1989/html_img/plot_page_Surface_Wind_Stress_SON_LatLon_Vector.html). I also fixed a quick bug that was keeping the plot image html files from being populated (probably got changed with all the newest PR's) but it's all good now and should be ready for a final look over and merge (fingers crossed!)

2022-05-05 19:17 UTC, nusbaume requested changes
Looks good!  However, I do have some change requests (mostly related to code-cleanup).

2022-05-05 19:17 UTC, nusbaume commented on scripts/analysis/amwg_table.py
> +        case = "Control"
In multi-case ADF runs the last entry in the case names list will be the baseline, and everything else will be a test case. I am not sure how you want to handle it at the moment (given that this function doesn't appear ready for multi-case usage yet?), but I would recommend setting the "Control" case to only be when `case_name = case_name_list[-1]`.

2022-05-05 19:17 UTC, nusbaume commented on scripts/analysis/amwg_table.py
> +    #preamble = f"""<html><head></head><body><h1>{f.stem}<h1>"""
Remove commented-out code?

2022-05-05 19:17 UTC, nusbaume commented on scripts/analysis/amwg_table.py
> +    </nav><h1>AMP Diagnostics</h1><h2>{case} Case: {f.stem}<h2>"""
I might change this header to be something like `Model Diagnostics`, `CAM Diagnostics`, or `ADF Diagnostics`.

2022-05-05 19:17 UTC, nusbaume commented on scripts/analysis/amwg_table.py
> +    </nav><h1>AMP Diagnostics</h1><h2>AMWG Case Comparison</h2><h2>Test Case: {case_names[0]}<br/>Control Case: {case_names[-1]}</h2>"""
I might change this header to be something like `Model Diagnostics`, `CAM Diagnostics`, or `ADF Diagnostics`.

2022-05-05 19:17 UTC, nusbaume commented on scripts/plotting/polar_map.py
> +                            #shfig.suptitle(f"{s} - {case_name} and {data_name}")
Remove commented-out code?

2022-05-05 19:17 UTC, nusbaume commented on scripts/plotting/polar_map.py
> +    #gs.update(wspace=0.9)
Remove commented-out code?

2022-05-05 19:17 UTC, nusbaume commented on scripts/plotting/polar_map.py
> +    #fig.suptitle("SEASON IN TITLE")
Remove commented-out code?

2022-05-06 19:23 UTC, justin-richling commented
@nusbaume I think I've gone through all your comments and have updated the branch. I just did a quick test with no issues so when you get a chance to it test on your end, let me know if anything else needs to be addressed.

Thanks again,

2022-05-12 16:06 UTC, nusbaume approved these changes

2022-05-12 16:07 UTC, merged