Add Taylor diags to the webpage
NCAR/ADF pull request #183
Opened 2022-06-15 22:47 UTC by cecilehannay

This PR adds the Taylor diags to the webpage. There are a few issues with the Taylor diags themselves (I will open an issue). But the issues should be independant from the mechanics of adding the Taylor diags to the webpage.

2022-06-16 17:51 UTC, nusbaume requested changes
Looks good!  I just have one change request.

2022-06-16 19:21 UTC, cecilehannay commented on lib/adf_diag.py
> +        var_list.extend(['cam'])
Good suggestion. I did the change.

2022-06-17 16:36 UTC, nusbaume approved these changes
Looks great now, thanks!

2022-06-17 16:38 UTC, nusbaume commented
@justin-richling just pinging you to see  if you could move the "missing webpage" fix to the top of your to-do list now.  Thanks!

2022-06-17 16:38 UTC, merged

2022-06-17 16:54 UTC, justin-richling commented
@nusbaume Thanks, I'm on it now. I should have a PR coming your way soon!