Refine the plot categories and define a default set of plots for amwg
NCAR/ADF pull request #204
Opened 2022-08-25 21:52 UTC by cecilehannay

I updated the plot categories so we don't have so many plots in a each category.
I also defined in config_amwg_default_plots.yaml the default set of variable we want to plot for amwg development.

2022-08-26 15:09 UTC, nusbaume requested changes
Looks good, but I did have some suggestions for the new config file that would be good to get your thoughts on.

2022-08-26 17:21 UTC, cecilehannay commented on config_amwg_default_plots.yaml
> +#config_cam_baseline_example.yaml
I agree. I changed that.

2022-08-26 17:22 UTC, cecilehannay commented on config_amwg_default_plots.yaml
> +    #You can alternatively provide a list of cases, which will make the ADF
Done

2022-08-26 17:24 UTC, cecilehannay commented on config_amwg_default_plots.yaml
> +#    - qbo
I am not sure I agree with that one. This is the default set of plots we are doing to evaluate cam7 runs for the AMWG.

2022-08-26 17:29 UTC, nusbaume commented on config_amwg_default_plots.yaml
> +#    - qbo
Sorry, "this entry" means explicitly the `qbo` plot.  If the QBO is supposed to be included as part of the CAM7 evaluation runs then should it be un-commented here?

2022-08-26 17:43 UTC, cecilehannay commented on config_amwg_default_plots.yaml
> +#    - qbo
Oh, it makes sense. I had deleted it already in the new file. So I think we are good to go. 
Thanks a bunch.

2022-08-29 16:58 UTC, nusbaume approved these changes
Everything looks good now.  Thanks @cecilehannay!

2022-08-29 16:59 UTC, merged