docstrings for plotting_functions.py
NCAR/ADF pull request #252
Opened 2023-08-03 23:39 UTC by brianpm

This PR is only for improved documentation of `plotting_functions.py`. 

It modifies all docstrings in the module.

Docstrings follow Numpy conventions: https://numpydoc.readthedocs.io/en/latest/format.html

I think I got everything. A few of them don't have as much info, but I think I pretty fully described the functions that users who will be trying to plug in their own scripts would need to see. 

Literally this just changes the docstrings, so I didn't do any testing because no code is altered.

2023-09-02 16:43 UTC, brianpm commented
Added docstrings for `global_latlon_map`

2023-10-05 03:21 UTC, nusbaume requested changes
This is great work!  Just found some minor typos.

2023-10-05 03:21 UTC, nusbaume commented on lib/plotting_functions.py
> +    bdata : xarray:DataArray
Typo here:

```suggestion
    bdata : xarray.DataArray
```

2023-10-05 21:01 UTC, brianpm commented on lib/plotting_functions.py
> +    Calculated the area-weighted RMSE.
✅

2023-10-05 21:02 UTC, brianpm commented on lib/plotting_functions.py
> +    Interpolate `data` from hybrid-sigma levels to isobaric levels.
✅

2023-10-05 21:03 UTC, brianpm commented on lib/plotting_functions.py
> +    Can provide multiple arguments.
✅

2023-10-05 21:04 UTC, brianpm commented on lib/plotting_functions.py
> +    When none of those three are found, raise and AdfError.
✅

2023-10-05 21:12 UTC, brianpm commented on lib/plotting_functions.py
> +    """
#262

2023-10-05 21:14 UTC, brianpm commented on lib/plotting_functions.py
> +        list of years in base case climatology
✅

2023-10-05 21:15 UTC, brianpm commented on lib/plotting_functions.py
> +        list of years in base case climatology
✅

2023-10-05 21:15 UTC, brianpm commented on lib/plotting_functions.py
> +    Currently it is inspecte for:
✅

2023-10-05 21:16 UTC, brianpm commented on lib/plotting_functions.py
> +    pressure derived with the forumla:
✅

2023-10-05 21:17 UTC, brianpm commented on lib/plotting_functions.py
> +    it is a lat-pres plot or  a line plot.
✅

2023-10-05 21:17 UTC, brianpm commented on lib/plotting_functions.py
> +    it is a lon-pres plot or  a line plot.
✅

2023-10-05 21:19 UTC, brianpm commented on lib/plotting_functions.py
> +    bdata : xarray:DataArray
✅

2023-10-05 21:25 UTC, nusbaume approved these changes
Looks great now, thanks!

2023-10-05 21:42 UTC, merged