Add V0 Ozone Diagnostics
NCAR/ADF pull request #285
Opened 2024-02-22 18:00 UTC by shawnusaf

Adds V0 ozone diagnostics that output ozone seasonal cycle and profile plots with model comparisons to ozone sonde climatology.

2024-02-22 18:00 UTC, shawnusaf commented
Addresses https://github.com/NCAR/ADF/issues/281

2024-05-31 20:17 UTC, justin-richling requested changes
Thanks for the work @shawnusaf, this is great to have. I just have some small changes for you to fix after which should be good to go. 

The biggest change requested is the move to using geocat for the hybrid to pressure interpolation. I have the updated code in the review, but let me know if you have any questions about it.

Let me know when you get the changes in and well move forward, thanks!

2024-10-11 14:13 UTC, shawnusaf commented
Changes have been addressed in the newly updated ozone_diagnostics.py file.  I have also added in taylor diagrams to the code.

2024-10-30 19:18 UTC, justin-richling commented on config_cam_baseline_example.yaml
> +user: 'shawnh'
This just needs to be changed back

2024-10-30 19:18 UTC, justin-richling commented on scripts/plotting/ozone_diagnostics.py
> +   test_nicknames = adfobj.case_nicknames["test_nicknames"]
@shawnusaf I would change this line so the plot legend isn't a list for the test case
![Screenshot 2024-10-30 at 1 15 30 PM (3)](https://github.com/user-attachments/assets/aaac4cad-b732-43a9-a282-eafc3e8b83da)

2024-10-30 19:23 UTC, justin-richling commented
@shawnusaf I left just a couple of suggestions, after that it should be good to merge in.

2024-10-31 14:18 UTC, merged