Update history string objects
NCAR/ADF pull request #316
Opened 2024-07-01 19:05 UTC by justin-richling

Clean up the history string objects in `adf_info.py`:
 - clean up naming of history string variables

 - Make baseline history info more robust; set default if not provided
 - Give full dictionary of test and baseline case(s) history string lists to adf object 

Update `tape_recorder.py` for new history string format:
 - Add check in history string lists for h0 time series files

Closes #315

2024-07-07 04:17 UTC, nusbaume requested changes
Looks good, but I did have a few questions and (hopefully minor) change requests.

2024-07-07 04:17 UTC, nusbaume commented on scripts/plotting/tape_recorder.py
> +    # - Search for either h0 of h0a
Typo:

```suggestion
    # - Search for either h0 or h0a
```

2024-07-07 04:17 UTC, nusbaume commented on scripts/plotting/tape_recorder.py
> +    for i,cam_case_str in enumerate(cam_hist_strs):
I believe `substrings` can be a set datatype, also it doesn't look like there is a need to `enumerate`:

```suggestion
    substrings = {"cam.h0","cam.h0a"}
    case_hist_strs = []
    for cam_case_str in cam_hist_strs:
```

2024-07-07 04:17 UTC, nusbaume commented on scripts/plotting/tape_recorder.py
> +        case_hist_strs.append(cam_hist_str[0])
If you are just trying to find the first match then I believe this code block can be simplified to:

```suggestion
        # Check each possible h0 string
        for string in cam_case_str:
            if string in substrings:
               case_hist_strs.append(string)
               break
```

2024-07-09 21:19 UTC, justin-richling commented
@nusbaume I got your suggestions done, but it looks like we still have some issues with the new history string implementation; the baseline history strings were not being brought over from the yaml file correctly. 

I have a quick addition in `adf_diag` that should take care of this bug, so if you wouldn't mind taking another quick look, thanks!

2024-07-11 17:07 UTC, nusbaume approved these changes
Everything looks great now, thanks @justin-richling!

2024-07-12 16:11 UTC, merged